package tech.rsqn.cdsl.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName="CdslContextIntegrationTest")
public class DynamoCdslContext { 
    private String id;
    private String contextId;
    private Date createdTs;
    private Date modifiedTs;
    private CdslContext context;

//DynamoDBVersionAttribute

    public DynamoCdslContext () {
        createdTs = new Date();
        modifiedTs = new Date();
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @DynamoDBHashKey (attributeName="id")  
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    
    @DynamoDBAttribute(attributeName="contextId")  
    public String getContextId() {
        return this.contextId;
    }
    
    public void setContextId(String contextId) {
        this.contextId = contextId;
    }
     
    
    public void setCreatedTs(Date d) {
        this.createdTs = d;
    }
    
    @DynamoDBAttribute(attributeName="createdTs")  
    public Date getCreatedTs() {
        return this.createdTs;
    }
    
    public void setModifiedTs(Date d) {
        this.modifiedTs = d;
    }
    
    @DynamoDBAttribute(attributeName="modifiedTs")      
    public Date getModifiedTs() {
        return this.modifiedTs;
    }   
    
    public void setContext(CdslContext ctx) {
        this.context = ctx;
    }
    
    @DynamoDBTypeConverted(converter = CdslContext.class)
    @DynamoDBAttribute(attributeName = "Context")
    public CdslContext getContext() {
        return this.context;
    }
   
}