package tech.rsqn.cdsl.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName = "CdslContextIntegrationTest")
public class DynamoCdslContext {
    private String id;
    private String contextId;
    private Date createdTs;
    private Date modifiedTs;
    private CdslContextDocument context;

    public DynamoCdslContext() {
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    @DynamoDBAttribute(attributeName = "contextId")
    public String getContextId() {
        return this.contextId;
    }

    public void setContextId(String contextId) {
        this.contextId = contextId;
    }

    public void setCreatedTs(Date d) {
        this.createdTs = d;
    }

    @DynamoDBAttribute(attributeName = "createdTs")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    public Date getCreatedTs() {
        return this.createdTs;
    }

    public void setModifiedTs(Date d) {
        this.modifiedTs = d;
    }

    @DynamoDBAttribute(attributeName = "modifiedTs")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getModifiedTs() {
        return this.modifiedTs;
    }

    public void setContext(CdslContextDocument ctx) {
        this.context = ctx;
    }

    @DynamoDBAttribute(attributeName = "context")
    public CdslContextDocument getContext() {
        return this.context;
    }

}
